package org.example.extraBuilder;

import com.squareup.javapoet.*;
import io.vavr.Tuple;

import javax.lang.model.element.Modifier;
import javax.tools.JavaFileObject;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import java.io.IOException;
import java.io.Writer;

public class GenMainClass {
    public static void genMainClass(GenerationConfig config){
        FieldSpec field = FieldSpec.builder(config.contentClassName(), "content")
                .build();

        AnnotationSpec xmlElement = AnnotationSpec.builder(XmlElement.class)
                .build();

        MethodSpec contentSetter = GenerationConfig.createSetter(Tuple.of(config.contentClassName(), field))
                .addAnnotation(xmlElement)
                .build()
                ;
        MethodSpec contentGetter = GenerationConfig.createGetter(Tuple.of(config.contentClassName(), field))
                .build()
                ;

        AnnotationSpec xmlRootElement = AnnotationSpec.builder(XmlRootElement.class)
                .addMember("name", "$S", config.getContainerClassStr())
                .build();
        TypeSpec mainClass = TypeSpec.classBuilder(config.getContainerClassStr())
                .addAnnotation(xmlRootElement)
                .addJavadoc("Generated by ExtraBuilderProcessor")
                .addModifiers(Modifier.PUBLIC)
                .addField(field)
                .addMethod(contentSetter)
                .addMethod(contentGetter)
//                .addMethod(main)
                .build();

        JavaFile javaFile = JavaFile.builder(config.getBasePackage(), mainClass)
                .build();

        try {
            JavaFileObject builderFile = config.getEnvironment().getFiler().createSourceFile(config.fullContainerClassStr());
            try (
                    Writer writer = builderFile.openWriter();
            ) {
                javaFile.writeTo(writer);
                writer.flush();
            } catch (IOException ex) {
                throw new RuntimeException(ex);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }

    }
}
